### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by ohreally** [dsoares/roundcube-lastlogin#28]
Hello,

After a PHP update, from 7.2.20 to 7.3.7, this plugin causes Roundcube to display only a blank page after login. Disabling this plugin gives me back RC.
Other packages were updated in the same go, but none of those relate to Roundcube.

Cheers,
  Rob

**Comment by dsoares** [comment]
I'll try to update. Thank you for alerting me to this issue.

**Comment by dsoares** [comment]
Hi,

Sorry for the late answer.
I've already tested the plugin with PHP 7.3. Did you install the PHP GeoIP extension after the upgrade to PHP 7.3 ?

**Comment by ohreally** [comment]
Hi,

Sorry for my late reply.
I really don't remember, and currently I'm really to busy to dive into this. If it's just for me, you may as well close this issue; I promise I'll check back once I have some time (which will not be before January, the way it looks now).

Sorry. And thanks for your time.

Rob

**Comment by knifegrinder** [comment]
Hi, I've installed the plugin but i get this error:

```
[10-Feb-2020 10:28:54 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function geoip_record_by_name() in /var/www/webmail/roundcube/plugins/geolocation/geolocation.php:119
Stack trace:
#0 /var/www/webmail/roundcube/plugins/geolocation/geolocation.php(67): geolocation::get_geolocation_info('213.218.53.172', 'system')
#1 /var/www/webmail/roundcube/plugins/lastlogin/lastlogin.php(418): geolocation->get_geolocation('213.218.53.172')
#2 /var/www/webmail/roundcube/plugins/lastlogin/lastlogin.php(135): lastlogin->get_geo('213.218.53.172')
#3 /var/www/webmail/roundcube/plugins/lastlogin/lastlogin.php(74): lastlogin->save_info()
#4 /var/www/webmail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(441): lastlogin->render_page(Array)
#5 /var/www/webmail/roundcube/program/include/rcmail_output_html.php(780): rcube_plugin_api->exec_hook('render_page', Array)
#6 /var/www/webmail/roundcube/program/include/rcmail_output_html.php(610): rcmail_output_html->parse('mail', false)
#7 /var/www/webmail/roundcube/index.php(315): rcmail_output_html->send('mail')
#8  in /var/www/webmail/roundcube/plugins/geolocation/geolocation.php on line 119
```

I've installed the required geoip2 plugin in roundcube but still having this error. Could be related to the old dsoares/geolocation requirement for this plugin when there's a new implementation?

TIA.

Fabio

**Comment by dsoares** [comment]
Hi,

The error is related to my other roundcube plugin dsoares/geolocation.  And yes, it's because i haven't upgraded it to geoip2.
`lastlogin` uses `geolocation` plugin if `lastlogin_geolocation` config option is set to `true` and this was the default. I've now changed if to `false` by default (Lastlogin release [1.3.0](https://github.com/dsoares/roundcube-lastlogin/releases/tag/1.3.0)), to avoid those errors. When geolocation becomes stable again, i'll turn it on again.

I'm going to close this issue because it is not related to this plugin. BTW, lastlogin works fine with PHP 7.3 and 7.4.
